// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:test_repo/features/cards/data/dto/card_dto.dart';
import 'package:test_repo/features/transactions/data/dto/transaction_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CardDtoAdapter());
    registerAdapter(TransactionDtoAdapter());
  }
}
